version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: "bash ./install.sh alpha"

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - store_artifacts:
          path: ~/repo/out/make
